# ------------------------------------------------------------------------------
# Function: Model Data Generation
# ------------------------------------------------------------------------------

generate_data <- function(n, dB = 2, dM = 3, dS = 1,
                          beta_tB, beta_MB, beta_Mt,
                          beta_rB, beta_rM,
                          eps_B_fun, eps_tr_fun, eps_M_fun,
                          pi1_fun) {
  
  X_B <- eps_B_fun(n)
  eps_tr <- eps_tr_fun(n)
  X_t <- X_B %*% beta_tB + eps_tr[, 1]
  eps_M <- eps_M_fun(n)
  X_M <-  X_B %*% t(beta_MB) + X_t %*% beta_Mt + eps_M
  X_r <- X_B %*% beta_rB + X_M %*% beta_rM + eps_tr[, 2]
  X_S <- matrix(rnorm(n * dS), n, dS)
  
  data <- data.frame(C = rep(NA, n), X_r = X_r)
  data$X_t <- X_t
  data$X_B <- I(X_B)
  data$X_M <- I(X_M)
  data$X_S <- I(X_S)
  
  # coarsen data
  pi1 <- pi1_fun(data[, c("X_B", "X_t")])
  pi2 <- pi2_fun(data[, c("X_B", "X_t", "X_M")])
  
  C <- rep(NA, n)
  for (i in 1:n) {
    p1 <- 1 - pi1[i]
    p2 <- pi1[i] * (1 - pi2[i])
    p3 <- pi1[i] * pi2[i]
    C[i] <- sample(c(1, 2, Inf), 1, prob = c(p1, p2, p3))
  }
  data$X_M[C == 1, ] <- NA
  data$X_r[C %in% c(1,2)] <- NA
  data$X_S[C %in% c(1,2)] <- NA
  data$C <- C
  
  return(data)
}


# ------------------------------------------------------------------------------
# Function: Parameter Estimation Functions
# ------------------------------------------------------------------------------

estimate_tB <- function(data) {
  solve(var(data$X_B) %*% (t(data$X_B) %*% data$X_B) , 
        var(data$X_B) %*%t(data$X_B) %*% data$X_t)
}

estimate_M <- function(data, beta_tB, pi1_fun) { 
  eps_t <- data$X_t - as.matrix(data$X_B) %*% beta_tB
  W <- ifelse(data$C >= 2, 1 / pi1_fun(data[, c("X_B", "X_t")]), 0) 
  
  fit <- lm(as.matrix(data$X_M) ~ data$X_t + as.matrix(data$X_B),
            weights = W)
  if (!is.matrix(coef(fit))) {  return(list(beta_Mt = as.matrix(coef(fit)[2]), beta_MB = t(coef(fit)[-c(1,2)]))) }
  list(beta_Mt = coef(fit)[2, ], beta_MB = t(coef(fit)[-c(1,2), ]))
}

estimate_parameters <- function(data, pi1_fun) {
  beta_tB <- estimate_tB(data)
  M_est <- estimate_M(data, beta_tB, pi1_fun)
  
  list(beta_tB = beta_tB,
       beta_Mt = M_est$beta_Mt,
       beta_MB = M_est$beta_MB
  )
}


# ------------------------------------------------------------------------------
# Function: compute residuals and moments needed for EIF variance and optimal pi
# ------------------------------------------------------------------------------

compute_moments <- function(data, estimates, pi1_0_fun) {
  X_B <- data$X_B
  X_t <- data$X_t
  X_M <- data$X_M
  C <- data$C
  beta_tB <- estimates$beta_tB
  beta_MB <- estimates$beta_MB
  beta_Mt <- estimates$beta_Mt
  gamma <- estimates$gamma
  eps_t <- X_t - X_B %*% beta_tB
  eps_M <- X_M - X_t %*% beta_Mt - X_B %*% t(beta_MB)
  
  # Moments
  var_eps_t <- var(eps_t)
  Weight_2inf <- ifelse(data$C >= 2, 1 / pi1_0_fun(cbind(X_B, X_t)), 0)
  var_eps_M <- cov.wt(eps_M[data$C >= 2, , drop = FALSE], wt = Weight_2inf[data$C >= 2])$cov
  
  avar_const_1 <- as.numeric(var_eps_M / var_eps_t^2)
  # only feasible for 1D M (or alternatively, aggregate asymptotic var matrix)
  
  list( 
    eps_t = eps_t,
    eps_M = eps_M,
    Weight_2inf = Weight_2inf,
    avar_const_1 = avar_const_1
  )
}

# ------------------------------------------------------------------------------
# Function: Asymptotic variance of the observed estimator Var(φ) on a dataset 
# generated by the functions pi1_0_fun, pi2_0_fun. 
# ------------------------------------------------------------------------------

compute_oif_variance <- function(data, estimates,
                                 pi1_0_fun,
                                 pi1_fun = NULL, 
                                 pi1 = NULL) {
  
  mom <- compute_moments(data, estimates, pi1_0_fun)
  if (!is.null(pi1_fun)) {pi1 <- pi1_fun(cbind(data$X_B, data$X_t)) }
  
  
  # First expectation term: average over all samples
  term1_mean <- mean(mom$avar_const_1 * (mom$eps_t^2) / pi1)
  
  return(term1_mean)
}

# ------------------------------------------------------------------------------
# Function: Compute the expected cost
# ------------------------------------------------------------------------------

# indicator: potential trimming of input vectors
compute_expected_cost <- function(pi1, c0, c1, 
                                  weight_2inf, indicator = NULL) { 
  if (!is.null(indicator)) { 
    term <- c0 + (pi1[indicator] * c1[indicator]) 
    weighted.mean(term, w = weight_2inf[indicator])
  } else {
    term <- c0 + (pi1 * c1)
    weighted.mean(term, w = weight_2inf)
  }
}

# ------------------------------------------------------------------------------
# Function: Determine the optimal \pi = (\pi_1, \pi_2) under budget
# ------------------------------------------------------------------------------

compute_optimal_pi <- function(data, estimates,
                               c0 = 0,
                               c1_fun,
                               b0,
                               pi1_0_fun, 
                               lambda_lower = 1e-8, lambda_upper = 1e8,
                               n_sub = 20000) {
  # Moments
  indicator_2inf <- data$C >= 2
  mom <- compute_moments(data, estimates,
                         pi1_0_fun)
  g1 <- (mom$eps_t)^2 * mom$avar_const_1
  c1 <- c1_fun(data[, c("X_B", "X_t")])
  
  # compute expected cost
  compute_expected_cost_lambda <- function(lambda) {
    enumeration_2inf <- which(indicator_2inf)
    
    pi1 <- pmin(1, sqrt(g1[indicator_2inf] / (lambda * c1[indicator_2inf])))
    
    compute_expected_cost(pi1, c0, 
                          c1_fun(data[enumeration_2inf, c("X_B", "X_t")]),
                          mom$Weight_2inf[indicator_2inf])
  }
  
  # Solve for lambda
  fn_root <- function(lambda) compute_expected_cost_lambda(lambda) - b0
  lower <- lambda_lower
  upper <- lambda_upper
  root <- tryCatch({
    uniroot(fn_root, lower = lower, upper = upper)
  }, error = function(e) {
    # value to adapt for computational speed
    grid <- 10^seq(-2, 2, length.out = 200)
    vals <- sapply(grid, fn_root)
    idx <- which(diff(sign(vals)) != 0)
    if (length(idx) == 0) stop("Failed to bracket lambda. Adjust b0 or costs.")
    uniroot(fn_root, lower = grid[idx[1]], upper = grid[idx[1] + 1])
  })
  lambda_star <- root$root
  
  # evaluate optimal control on the given dataset
  pi1_star_fun <- function(data, lambda) {
    c1 <- c1_fun(data[, c("X_B", "X_t")])
    eps_t <- data$X_t - data$X_B %*% estimates$beta_tB
    g1 <- (eps_t)^2 * mom$avar_const_1
    
    pi1 <- pmin(1, sqrt(g1 / (lambda_star * c1)))
  }
  
  list(
    lambda_star = lambda_star,
    pi1_star = pi1_star_fun(data, lambda_star),
    pi1_star_fun = pi1_star_fun
  )
}
